### ISSUE TITLE
[MPI_Resources_bug]: runnning the model gives an error #409

### ISSUE THREAD

**Issue by jroachell15** [Pandora-IsoMemo/resources#1]
Original ticket: https://github.com/INWT/mpi-resources/issues/409

running the Montecorvino and San Lorenzo Single Values file (attached) and then, after a while, I received this error (attached figure). I tried twice and the same happened. (file is here: https://drive.google.com/drive/folders/1f_vifZAmXYX4djgiWCEKMtHvOwTp8NRJ)

![image](https://user-images.githubusercontent.com/73887426/152498896-94c6a57c-4097-4bf4-815a-91216b60a6e9.png)

@mgross said:
that bug is puzzling me. It has to do with the priors and C gives a compilation error that is very strange. I tried to find out what is wrong this evening, but I couldn't. The first prior which is ok, while the second is not compiling and it's not clear to me why. First one translates to:

```
dconstraint((alpha_[1, 1] + alpha_[2, 1] + alpha_[3,
        1] + alpha_[4, 1] + alpha_[5, 1] + alpha_[6, 1] + alpha_[7,
        1] + alpha_[8, 1] + alpha_[9, 1] + alpha_[10, 1])/10 >
        (alpha_[1, 2] + alpha_[2, 2] + alpha_[3, 2] + alpha_[4,
            2] + alpha_[5, 2] + alpha_[6, 2] + alpha_[7, 2] +
            alpha_[8, 2] + alpha_[9, 2] + alpha_[10, 2])/10)
```

second one to:
```
dconstraint((alpha_[11, 1] + alpha_[12, 1] +
        alpha_[13, 1] + alpha_[14, 1])/4 > (alpha_[11, 2] + alpha_[12,
        2] + alpha_[13, 2] + alpha_[14, 2])/4)
```
I will further investigate this.

Ricarod said: 
I have a suggestion, test this with only the second prior and successively eliminate its components to try to isolate the source issue.

Marcus:
Yes, I am trying to reduce the problem to the core. It could be, however, that the problem is a bug in the underlying Bayesian software (in that case I'll contact the developers).

- [ ] Follow up with marcus

**Comment by arunge** [comment]
@mgross pushed some changes https://github.com/Pandora-IsoMemo/resources/commit/f9ac34f8cca5444477502b88e0d789ab2a32c1da to the main that hopefully will solve the problem here.

**Comment by arunge** [comment]
@isomemo we added a fix to both [main](https://isomemoapp.com/app/resources) and [beta](https://isomemoapp.com/app/resources-beta)
Could you test if the problem mentioned [above ](https://github.com/Pandora-IsoMemo/resources/issues/1#issue-1145530130) still occurs?

**Comment by arunge** [comment]
@isomemo Could you please check if all here is correct now? If you do not request any further adjustments, we will close this issue in one week.

**Comment by isomemo** [comment]
According to Carlo this is now working!
