### ISSUE TITLE
Issue with user estimates

### ISSUE THREAD

**Issue by CarloCocozza** [Pandora-IsoMemo/resources#100]
[2023-08-28_16_48_18_fruitsModel.zip](https://github.com/Pandora-IsoMemo/resources/files/12455781/2023-08-28_16_48_18_fruitsModel.zip)
![Bug resources User Estimates](https://github.com/Pandora-IsoMemo/resources/assets/101706974/bdc45c20-6d97-414f-b0b0-f5cfb13c318c)

For the attached model, the attached error message appears when user estimates are included.

@arunge

**Comment by mgross** [comment]
@CarloCocozza @arunge:

I looked into it and it because the 10 and 11th user estimates state "herbivore" instead of "herbivores". The translatePriors()-function produces NA's then. @arunge: one could catch the NA's and post a warning and filter them out or post an error

**Comment by CarloCocozza** [comment]
> @CarloCocozza @arunge:
> 
> I looked into it and it because the 10 and 11th user estimates state "herbivore" instead of "herbivores". The translatePriors()-function produces NA's then. @arunge: one could catch the NA's and post a warning and filter them out or post an error

My bad!
Thank you!

**Comment by arunge** [comment]
@mgross When removing the NA value(s) the model seems to run, but in the end there is another error:

![image](https://github.com/Pandora-IsoMemo/resources/assets/16759098/0703d32f-48f6-4748-a30b-a8e9b94776e6)

So, this is not all that must be done here. Could you help to catch the problem: https://github.com/Pandora-IsoMemo/resources/pull/101/files ?

Additionally, creating a meaningful warning is not that simple. Currently, I can only tell that there was a `NA` and that I removed it.
![image](https://github.com/Pandora-IsoMemo/resources/assets/16759098/c152962a-5477-45a2-a0b8-00454fd031f9)

However, is there a chance to identify which of the priors caused the problem?

`grep(x = templateEvaluated, pattern = "NA")` only tells me the line of the NA, which is `215` with the data from above. Is it possible to get the respective prior from that?

There are several values that are used to create `templateFilled`.

```R
templateFilled <- tmpl(nimbleTemplate,
    likelihood = likelihood,
    priorAlpha = priorAlpha,
    combineSources = combineSources,
    priorSources = priorSources,
    priorSourceOffsets = priorSourceOffsets,
    priorOffsets = priorOffsets,
    priorConcentrations = priorConcentrations,
    priorWeights = priorWeights,
    userDefinedPriors = userDefinedPriors,
    userDefinedEstimates = userDefinedEstimates
  )
```

How is the creation of the template working, where does line `215` come from?

**Comment by mgross** [comment]
@arunge: the NA's happen in the translatePriors() function, when you userDefinedPriors are generated. Will look into the rest when I have time

**Comment by mgross** [comment]
@arunge: When removing both user estimates in the app, the model runs for me; so maybe a glitch?

For a potential fix,see :https://github.com/Pandora-IsoMemo/resources/pull/103

**Comment by arunge** [comment]
With [version 23.07.1](https://github.com/Pandora-IsoMemo/resources/pull/104) on Resources [main](https://isomemoapp.com/app/resources) and on [beta](https://isomemoapp.com/app/resources-beta) we catch the case when prior names are not found or do mismatch with an error message. This should help to identify and avoid inconsistencies in prior names.
