### ISSUE TITLE
Error with user estimates

### ISSUE THREAD

**Issue by CarloCocozza** [Pandora-IsoMemo/resources#109]
[2023-11-13_13-46-18_model.zip](https://github.com/Pandora-IsoMemo/resources/files/13334938/2023-11-13_13-46-18_model.zip)
![BUg User estimates X](https://github.com/Pandora-IsoMemo/resources/assets/101706974/53bfe2e8-d043-4f73-b1e3-ca7467d13e03)

For the attached model, when user estimates are added, the attached error message pops up.

Note: I had to change the extension of the file from .resources to .zip so that I could upload it to github.

@arunge

**Comment by arunge** [comment]
@mgross Please, help with this bug. With the data from above the error occurs in the function `normalizeUserEstimates()` after the model run in the following lines

https://github.com/Pandora-IsoMemo/resources/blob/67089403999dc41eae9929367bcb2e7eb544dbaa/R/04-runModel.R#L273-L295

With the data from above, 
- the `length(groupNames) == 1`
- in the `split()` function the `x` value is much shorter than the `factor` variable for the grouping, which gives empty groups:
  ```R
    list(`1` = 1L, `2` = 2L, `3` = 3L, `4` = integer(0), `5` = integer(0), 
    `6` = integer(0), `7` = integer(0), `8` = integer(0), `9` = integer(0), 
    `10` = integer(0), `11` = integer(0), `12` = integer(0), 
    `13` = integer(0), `14` = integer(0), `15` = integer(0), 
    `16` = integer(0), `17` = integer(0), `18` = integer(0), 
    `19` = integer(0))
  ```
- therefore `cbind` crashes

What should be done in this case?
- Do we have too little columns in `est`? Why? What does this mean for the model?
  - Should the case be excluded?
  - Or, is this a valid case of inputs, and a new condition should handle this case?

Please, advice here from modelling perspective! Thanks in advance!

**Comment by CarloCocozza** [comment]
Hi @mgross @arunge,

Are there any updates on this bug? I still face the same problem and I really need to use User Estimates in my models as soon as possible.

**Comment by arunge** [comment]
@CarloCocozza Sorry, but I have not yet any updates from @mgross here. I am trying to reach him. Thanks for your patience!

**Comment by mgross** [comment]
@CarloCocozza: I think I found the issue. @arunge will look at it and it should work soon.

**Comment by arunge** [comment]
Thanks @mgross for your help here!

@CarloCocozza With [version 23.12.1](https://github.com/Pandora-IsoMemo/resources/pull/111) on [Resources beta](https://isomemoapp.com/app/resources-beta) the fix is now online. Thanks for your patience!
