### ISSUE TITLE
Importing Models does not work

### ISSUE THREAD

**Issue by sarahdefant** [Pandora-IsoMemo/resources#112]
@isomemo 

Importing models (created between October 2023 and now) into the ReSources App, doesn't seem to work.
I can select the file after which it loads the input data, model selection parameters and the results. But when clicking "Accept", it gets stuck on the loading screen (see Screenshot) and won't actually display any of the model data. 

<img width="1440" alt="Screenshot 2024-04-24 at 09 55 40" src="https://github.com/Pandora-IsoMemo/resources/assets/167770119/64dcbbd5-9a36-477a-87d3-adddb61fbad8">

**Comment by arunge** [comment]
@sarahdefant I am maintaining ReSources and will have a look into this issue. Thank you for reporting the problem and also for your patience. I will return to you soon.

**Comment by arunge** [comment]
@sarahdefant Currently, there is indeed an issue with the import of models on the [main version of ReSources](https://isomemoapp.com/app/resources). However, when testing model import on our beta version I had no issues.

Could you please try the download and import of models on our beta version?
https://isomemoapp.com/app/resources-beta

Possibly the import of the model object from version 23.7.1 (your screenshot above) might fail. If so, please re-run your model on the beta version and try to download a new model object.

Please let me know if this works. If so, I would just update our main app (version 23.7.1) to the most recent version from beta (23.12.1).

**Comment by sarahdefant** [comment]
@arunge Thank you so much for addressing this so quickly. 

I have rerun the model on the Beta version and now the download and Import seem to work seamlessly. (:

As presumed, the import of older model objects from the 23.7.1 version does not work on the Beta version, though. 

Thank you!

**Comment by arunge** [comment]
The version 23.12.1 is now also online on our [main app](https://isomemoapp.com/app/resources) and model import should work also here. I am closing this issue.
