### ISSUE TITLE
[resource_bug]: model cannot be uploaded and app crash when deleting a column 

### ISSUE THREAD

**Issue by jroachell15** [Pandora-IsoMemo/resources#12]
@arunge 
I try to debug one of the issues with Carlo, the research assistant of Ricardo, when he reported that there was a problem with uploading and editing the rows/columns.  

Carlo's email: @CarloCocozza 
_**I wanted to create a thread on github for this, but I cannot attach RData files there.

In ReSources, in both online and local versions, the app crashes when I try to edit or delete rows/columns in the covariate table in Data. This happens systematically for previously saved models (such as the one attached) or more randomly in new models when you get back to the table after a while.**_

Here is the file: https://drive.google.com/file/d/1NAKhb4xbO_kFogDlexEAmNo90lzIAtJT/view?usp=sharing

![image](https://user-images.githubusercontent.com/73887426/160081850-f166f264-c45d-4446-8aa9-1b41cc81d124.png)
it is the model is uploaded complete, but then I receive this message:

![image](https://user-images.githubusercontent.com/73887426/160079285-47ff901a-97f0-423f-8976-3700fffceb01.png)

Please let me know if I am uploading the file correctly?

**Comment by arunge** [comment]
@jroachell15 The file you linked for uploading is not a `.zip` file, but an `.RData` file. 

![image](https://user-images.githubusercontent.com/16759098/160086286-7f215bc4-c7c0-40f4-84ee-c5ddaaae1656.png)

Currently, the app expects a .zip file, e.g. (1) that was previously generated by downloading a model with the following content (2):

![image](https://user-images.githubusercontent.com/16759098/160086648-f98b5d8f-0f85-407a-921f-e9c19805bb8f.png)

However, the format of the `.RData` file seems to be the same as it is currently of the `model.rds` file:
![image](https://user-images.githubusercontent.com/16759098/160087470-46bcd555-9f17-45fc-a948-6a2bf966f64d.png)

I could add the possibility that the app is able to read the `.RData` file again. But the disadvantage is that .RData files are loaded into the global environment, which can always be dangerous, while .rds files are stored under a chosen name in the local environment where it is called (much saver).
Additionally, the `.zip` stores also the `README.txt` which is used to update "Notes" text field.

Please use only files for uploading which where downloaded as a `.zip` file.

If @CarloCocozza really needs exactly this model, I could implement a function that translates the `.RData` file into the correct format (the `.zip` file). But this needs to be confirmed by @isomemo .

**Comment by arunge** [comment]
@jroachell15 : I will update the pop up contnent as discussed.

**Comment by jroachell15** [comment]
@CarloCocozza 

Please upload the model again (in zip file format) here: https://drive.google.com/file/d/1DYtUav182B_WQ8MEaN1iHuQvasG1gNAy/view?usp=sharing

I have also tried to enter new fields into the Covariates table and it looks fine, but I DO confirm that the app crashes when I try to delete a column:
![image](https://user-images.githubusercontent.com/73887426/160097756-84ff969f-ad31-4bc7-ace1-af97a7dd37aa.png)

the app did crash. 

We will try to fix this issue soon. thanks for your patience!

**Comment by CarloCocozza** [comment]
@jroachell15 How can I convert the RData into zip file? I tried some online convertors but this didn't work. Also, is this why in the beta version I could not upload a previous saved model?

**Comment by arunge** [comment]
I updated the text of the pop up with version 22.03.7.

**Comment by jroachell15** [comment]
@CarloCocozza did you solve this issue? there are three files that needs to be in the zip file (the modelRdata, readMe.txt, and help.html), these additional files can be made with text editor. highlight the 3 files, and right click, then there is an option to make them into a zip file. Let me know if this is successful. Thanks! 

if there is no more issues, I will close this ticket.

**Comment by CarloCocozza** [comment]
@jroachell15 I apologise, I thought you uploaded the zip file already! I only have the modelRdata, what readMe.txt and help.html files do you need? and how do I get these from the model? I was not using the beta version for that model because I could not upload the modelRdata file there with the new update. Anyway, as you also noticed, this bug was systematic and not model-related.

**Comment by arunge** [comment]
Update and note for me regarding:

> In ReSources, in both online and local versions, the app crashes when I try to edit or delete rows/columns in the covariate table in Data. This happens systematically for previously saved models (such as the one attached) or more randomly in new models when you get back to the table after a while.

from https://github.com/Pandora-IsoMemo/resources/issues/12#issue-1180482323

The issue also occurs simply with the example data: "Five Sources Data". Trying to delete the column `country` directly after loading the data leads to a crashing of the app. I could identify, at which point the error occurs:

- deleting `Nitrogen` in the first table works as expected, and in 
https://github.com/Pandora-IsoMemo/resources/blob/ac6e53581677d33a3185adceac5d33c6a9e9241c/R/02-fruitsMatrix.R#L535
https://github.com/Pandora-IsoMemo/resources/blob/ac6e53581677d33a3185adceac5d33c6a9e9241c/R/02-fruitsMatrix.R#L538
`inputData()[[1]] == meanData()` both are already updated and without the deleted column:
![image](https://user-images.githubusercontent.com/16759098/178476243-d81016ab-773e-49bd-9556-f58b1cf8bca6.png)
- However, deleting `country` in the Covariates Table gives:
https://github.com/Pandora-IsoMemo/resources/blob/ac6e53581677d33a3185adceac5d33c6a9e9241c/R/02-fruitsMatrix.R#L564-L565
not equal `inputData()` and `meanData()`:
![image](https://user-images.githubusercontent.com/16759098/178476795-abdaaf01-c073-479c-a5ca-fdc5ad966796.png)
This leads to an error in
https://github.com/Pandora-IsoMemo/resources/blob/ac6e53581677d33a3185adceac5d33c6a9e9241c/R/02-fruitsMatrix.R#L570-L574

It looks like an update for `meanData()` is not working.

**Comment by arunge** [comment]
> Feel free to set the format of the saved file. The key point to remember is that this should save all data inputs (and optionally results).

Already there, but the default is to store everything:
![image](https://user-images.githubusercontent.com/16759098/178996712-6cd0b2fb-b620-4cdc-9386-41cbca87eb81.png)

> You could add a header text to saved file(s) that identifies the version of the saved file so that after certain updates to the app only files from a certain version onward can be uploaded. We could also make this more refined by having two options: prevent loading (if version too old) but if possible (for not so old files) loading could be allowed but a warning is issued that this may cause the app to malfunction.

The version number is currently already stored in the model object. I will print the version number inside the message box _with the **next** update_:
![image](https://user-images.githubusercontent.com/16759098/178997351-6b2220ad-1f70-4321-b09f-21ecc012627c.png)

Currently, I will not restrict the upload to a particular minimum version number. If we will have more issues here, I can add a restriction later.

I close here for now.
