### ISSUE TITLE
Probable issue with labels - User Estimates

### ISSUE THREAD

**Issue by CarloCocozza** [Pandora-IsoMemo/ReSources#125]
In the new versions, I cannot find categories in User Estimates that are pertinent to Source-Component. E.g. "C3-Protein", where C3 is a source and Protein is a component. Example model is here attached. This was present in the past versions. Could it be an issue with component labels not being transferred?
[model.resources.zip](https://github.com/user-attachments/files/16285472/model.resources.zip)

I also uploaded an old model where these labels were present. I can see that these labels are saved in the User Estimates (and also Priors) but cannot be found among the options below. I attached the old model too.
 
[Montecorvino and San Lorenzo Model.zip](https://github.com/user-attachments/files/16285478/Montecorvino.and.San.Lorenzo.Model.zip)

@arunge

**Comment by arunge** [comment]
@CarloCocozza The labels havn't been updated correctly. This is fixed now and missing categories should be available with [version 24.08.1](https://github.com/Pandora-IsoMemo/ReSources/pull/128) which is online on [ReSources beta](https://isomemoapp.com/app/resources-beta). Thanks for reporting this issue!
