### ISSUE TITLE
Model crashes when covariates are selected in the output section

### ISSUE THREAD

**Issue by CarloCocozza** [Pandora-IsoMemo/ReSources#126]
The attached model crashes, after running correctly, when in the output section I select "display by" and choose a covariate. I am using the Beta version online 24.7.0.3. This is not limited to this model.
[Schwetzingen.zip](https://github.com/user-attachments/files/16496128/Schwetzingen.zip)

@arunge

**Comment by arunge** [comment]
Here I could reproduce the issue locally and receive following error:

```
Warnung: Error in [: Indizierung außerhalb der Grenzen
  52: <Anonymous>
  51: which [/home/.../resources/R/03-plotTargets.R#312]
  50: getTeaser [/home/.../resources/R/03-plotTargets.R#312]
  49: <Anonymous> [/home/.../resources/R/03-plotTargets.R#44]
  47: plotFun() [/home/.../resources/R/02-outputPlot.R#245]
  46: observe [/home/.../shiny-tools/R/02-plotExport.R#105]
  45: <observer>
   2: runApp
   1: startApplication [/home/.../resources/R/00-startApplication.R#8]
Warnung: Error in plot
 error: Indizierung außerhalb der Grenzen
```

@CarloCocozza I will let you know, when the fix is online.

**Comment by arunge** [comment]
@CarloCocozza The fix in the plotting function is online with [version 24.08.0](https://github.com/Pandora-IsoMemo/ReSources/pull/127) on [ReSources beta](https://isomemoapp.com/app/resources-beta).
