### ISSUE TITLE
[MPI_Resource_ bug]: when switching datasets the covariates still remain visible #408

### ISSUE THREAD

**Issue by jroachell15** [Pandora-IsoMemo/resources#2]
original ticket: https://github.com/INWT/mpi-resources/issues/408

Carlo, Ricardo's research assistant first reported the bug:

I loaded the Montecorvino and San Lorenzo file (attached) and then I loaded the Capitanata mean values file (also attached). The prior options for the first file when it comes to covariates remained visible. 

the files for testing are here: https://drive.google.com/drive/folders/1f_vifZAmXYX4djgiWCEKMtHvOwTp8NRJ

Feedback from Ricardo and Marcus: 

_Ricardo_: 

When one resets (button) ReSources this should revert to default model options. Similarly, when one loads a model file it should obviously load only the saved options for that model. What Carlo was describing is the following:

1) one loads a model X
2) one then loads a different model Y. This operation should clean inputs from model X and show only inputs for Y
3) However, and this was what Carlo was referring to, after loading model Y some values from model X remain in the prior interface
4) the above will cause the app not to run and/or originate erroneous results

Please address this as I had a previous task to ensure that loading of a model results in interface values that were set when saving it. Andreas might also be able to address this since this is a simple interface issue (reset not being properly made when loading a new file although when one presses the reset button this is working properly).

_Marcus_:
This is certainly a bug. I would for now recommend just to restart the app when having a different model. However, that issue should be relatively easy to solve for Andreas.

_Ricardo_: 
My suggestion would be simply to call the reset function whenever a file is loaded prior to loading the new model inputs.

_Marcus_:
Reset call might work, but I think there are still some of the same issues present.

- [ ] Follow up with @mgross  to see what is the next step to fix this bug. (track this time in MPI_2022 project)

**Comment by arunge** [comment]
The bug was fixed on beta and main.
Only the input fields were not updated, the values in the backend had been updated always when data was uploaded.
In Shiny values of NULL will not lead to any updates of the choices parameters, see https://github.com/Pandora-IsoMemo/resources/pull/9#issue-1157208899.

**Comment by arunge** [comment]
@isomemo The same issue occured in the tab "User estimates" for the corresponding select input fields. Maybe, this was the reason, that it looked like the reset button worked not correctly?
This issue in the tab "User estimates" was fixed within this changes, also.
