### ISSUE TITLE
Error in simple two-end member model

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/resources#21]
I have a simple two end model:
a) One individual with proxy 1 (only proxy) value of 5 (no uncertainty)
b) Model without concentrations or components (all other model options as default)
c) Two food sources with values for proxy 1 of 0 and 10

Running the model the following error in thrown:

Could not run model. Received the following error: Error in colMeans(allsamples[, grepl("mu\\[", colnames(allsamples))]) : 
  'x' must be an array of at least two dimensions

**Comment by isomemo** [comment]
Working now!

**Comment by arunge** [comment]
Merge beta with fixes into main. Available with version: 22.06.3
