### ISSUE TITLE
Target & Source summary

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/resources#25]
I selected the 5 sources example. Under "Model characteristics" I performed a simulation for all sources. Following this, I selected "Target & Source summary" and got the following error:

length of 'dimnames' [2] not equal to array extent

**Comment by mgross** [comment]
I couldn't replicate the error with 22.6.1

**Comment by isomemo** [comment]
I got again the same error. See this video: https://youtu.be/KgcqB5R3-7g

Did you try this on 22.6.1 Beta version?

**Comment by arunge** [comment]
@isomemo I checked the steps in the video.

With [version 22.6.4.2 on the main](https://isomemoapp.com/app/resources) I could reproduce the error:

![image](https://user-images.githubusercontent.com/16759098/201351544-2e852fe3-86b4-4e97-b142-03561d7d2be9.png)


With [version 22.11.2 on the beta branch](https://isomemoapp.com/app/resources-beta) I could not reproduce it:

![image](https://user-images.githubusercontent.com/16759098/201350358-8556705b-c7e5-488e-965f-0fd898747122.png)

Most likely, @mgross fixed the issue within other bug fixes, in the meanwhile.

If we [push the changes from the beta to the main](https://github.com/Pandora-IsoMemo/resources/issues/60), this issue will be solved. I close here.
