### ISSUE TITLE
[MPI_task2022]: Resources. reset button that resets the contents of that table only. #407

### ISSUE THREAD

**Issue by jroachell15** [Pandora-IsoMemo/resources#3]
ReSources (~ 3 h)
Original ticket: https://github.com/INWT/mpi-resources/issues/407

For each input table a reset button that resets the contents of that table only. The default scale for all estimates should be between 0 and 100.

**Comment by jroachell15** [comment]
After `browser()` the code,

I find the `vars` mapping of the list that populate the tables:
![image](https://user-images.githubusercontent.com/73887426/178718740-eb36ded2-6fa9-4d64-8ef5-a17124ec12fa.png)

@arunge next step I need help breaking down the data structure of the individual tables, then finally apply the `reset` button to each table. 

something like this:

reset <- function(table){
input$values <- 0
}

apply to every table. 

- need to find where is every table in server.R

**Comment by jroachell15** [comment]
@arunge transfer this task to you. work with this branch: https://github.com/Pandora-IsoMemo/resources/tree/feat/3_resetButton

**Comment by arunge** [comment]
remove only content, not row/column names

**Comment by arunge** [comment]
@iso the reset button for a single table is online on [beta](https://isomemoapp.com/app/resources-beta) with [version 23.05.1](https://github.com/Pandora-IsoMemo/resources/pull/93)

![image](https://user-images.githubusercontent.com/16759098/235991943-0b5613de-cbd2-4f3e-a4e9-d5f13fc3a667.png)
