### ISSUE TITLE
Bug with Priors

### ISSUE THREAD

**Issue by CarloCocozza** [Pandora-IsoMemo/resources#30]
![bug prior 2](https://user-images.githubusercontent.com/101706974/172148419-f75b11db-c7b5-4e8b-9426-59d1dafe1a99.PNG)
![Bug priors](https://user-images.githubusercontent.com/101706974/172148423-50e0faa4-710b-4e2d-9ee6-0d5a782f4dfa.PNG)
[2022-06-01_17_32_45_fruitsModel.zip](https://github.com/Pandora-IsoMemo/resources/files/8843899/2022-06-01_17_32_45_fruitsModel.zip)

For the attached model, I get a bug if I include in the model the last two priors (see figures)
@arunge

**Comment by jroachell15** [comment]
@CarloCocozza @arunge 

I confirm that you do indeed get this warning message, however I don't know whether this is a bug. This says please check your priors. These two priors, what do they mean?
![image](https://user-images.githubusercontent.com/73887426/172615380-2b73c596-3e32-4b6a-913e-f47f1c2c2c3c.png)

@mgross maybe you can help comment on this? thanks!

**Comment by CarloCocozza** [comment]
@jroachell15 These priors were set by Ricardo. However, they were set using the categories below in the prior section. So I guess it is a bug.

**Comment by mgross** [comment]
Fixed in the next version

**Comment by CarloCocozza** [comment]
@arunge just checked this other issue. It runs now, thanks!
