### ISSUE TITLE
potential Bug with covariate estimates

### ISSUE THREAD

**Issue by CarloCocozza** [Pandora-IsoMemo/resources#31]
[2022-06-06_13_25_02_fruitsModel.zip](https://github.com/Pandora-IsoMemo/resources/files/8844028/2022-06-06_13_25_02_fruitsModel.zip)
For the attached model, the estimates when running a model without covariates are similar for the two included targets. However, if running the model again with covariates the new estimates differ considerably with the previously.

@mgross 
@arunge

**Comment by arunge** [comment]
@mgross Could you check this issue, since it is reltatet to the model and model results?

**Comment by mgross** [comment]
Additional remark:
According to https://arxiv.org/pdf/1504.02689.pdf  0.8 * 1/nSources is the optimal objective prior (1/7 * 0.8 ~ 0.114) for the dirichlet. For this, the results are virtually the same for both models.

**Comment by isomemo** [comment]
@mgross 

Thanks Marcus! Would you recommend in general the use of an objective prior?

Also, I am preparing a list of new tasks for INWT, I had included the possibility of the  user assigning individual hyperparameter values for the dirichlet (with number of inputs matching number of sources). Currently only a single uniform value can be assigned. In addition, we could have some main options to set hyperparameters. For instance, the use of an objective prior as above or of a constant value (1) as it is now. 

I would imagine that the above is quite simple to be done and can be done by INWT (just requires identifying the array where hyperparameters are stored). Or am I wrong?

**Comment by mgross** [comment]
Ok, this wasn't that much work:
I introduce a checkbox "optimal objective prior" (checked as default, now results are more extreme in general as prior is much weaker and the data has more influence). If selected the hyperparameter (prior) value choice box disappears and 0.8*1/nSources is internally used as alpha vector.

@arunge I made a pull request into beta

**Comment by isomemo** [comment]
@mgross thank you! I would like to ask you to do one more thing (please use time from our contract). Can you please give the user the option of assigning hyperparameter values by source? At the moment the user can only assign the same value to all sources. 

The default value for all should remain 1.

The difficulty, I would imagine, is that users may change the number of sources after assigning the hyperparameter values. But in this case please follow the simplest of options (e.g. values remain the same as prior to the change, or these are reset back to 1)

**Comment by arunge** [comment]
> @mgross thank you! I would like to ask you to do one more thing (please use time from our contract). Can you please give the user the option of assigning hyperparameter values by source? At the moment the user can only assign the same value to all sources.
> 
> The default value for all should remain 1.
> 
> The difficulty, I would imagine, is that users may change the number of sources after assigning the hyperparameter values. But in this case please follow the simplest of options (e.g. values remain the same as prior to the change, or these are reset back to 1)

@isomemo Regarding the above, should I open a new issue for this so that I can close this one?

**Comment by isomemo** [comment]
@isomemo what is being requested from me here?

**Comment by arunge** [comment]
I was refering to the task for @mgross in https://github.com/Pandora-IsoMemo/resources/issues/31#issuecomment-1172327753

**Comment by arunge** [comment]
The issue of assigning hyperparameters will be one of the new tasks. We can close here.
