### ISSUE TITLE
Copy paste bug

### ISSUE THREAD

**Issue by CarloCocozza** [Pandora-IsoMemo/resources#33]
![Bug copy paste](https://user-images.githubusercontent.com/101706974/172159501-b8bf6761-1a43-463f-bd76-05db02b127b1.PNG)
[Tertiveri Model.zip](https://github.com/Pandora-IsoMemo/resources/files/8844398/Tertiveri.Model.zip)

For the attached model I pressed the button copy to copy the values for the covariance matrix (under "target & target-to-source offset"). When I try to paste these elsewhere the first column is empty

@arunge

**Comment by jroachell15** [comment]
@CarloCocozza I have tried to copy and paste functino from the table you indicated and it seems to be fine with me as I pasted the table into the first two tables:

![image](https://user-images.githubusercontent.com/73887426/172618658-916ff0b6-2433-4a9d-9e2f-b0867724bcb6.png)

First of all, after the paste, the first column is not empty bc the 0.55, -0.32, -.18 values still are pasted. correct? 
what do you mean by "elsewhere"? where did you try to paste it?

**Comment by jroachell15** [comment]
@CarloCocozza 

thanks for your patience. I am still not successful. the only issue I saw was when i try to paste the values back into the `Observation - Target Covariance Matrix` which indeed has a copy paste problem. @arunge please let me know if this copy and paste issue can be fixed for the this table?

**Comment by jroachell15** [comment]
@CarloCocozza 

We have successfully fixed the copy and paste bug. Please test the Beta version with the same dataset here:

https://isomemoapp.com/app/resources-beta

will close this issue, if you don't find any other bugs with this.
