### ISSUE TITLE
Potential bug related with estimates using covariance matrices

### ISSUE THREAD

**Issue by CarloCocozza** [Pandora-IsoMemo/resources#36]
[2022-06-06_16_28_47_fruitsModel.zip](https://github.com/Pandora-IsoMemo/resources/files/8845120/2022-06-06_16_28_47_fruitsModel.zip)

For the attached model, the estimates for source "C4 cereals" for the target "cluster 1" should be larger than "cluster 2" while the reverse should be the case for the source "marine resources". 

When using normal distributions for the targets, the above is observed, although the differences are negligible. However, when using covariance matrices, the opposite is observed.

The covariance matrices represent the variance for the two targets and the individual entries for each are given in the attached excel file. 

It is unclear if this is a bug or not.

@mgross 
@arunge 
[Clusters.xlsx](https://github.com/Pandora-IsoMemo/resources/files/8845168/Clusters.xlsx)

**Comment by mgross** [comment]
The model code seems correct to me. There is strong correlation in the covariance matrix, thus different results can very much be. (you can enforce your knowledge by priors, though)

**Comment by arunge** [comment]
@CarloCocozza is there still any open question here? If not, feel free to close the issue.

**Comment by arunge** [comment]
@CarloCocozza I assume, all is done here. If not, please feel free to open a new ticket.
