### ISSUE TITLE
Bug with User estimates

### ISSUE THREAD

**Issue by CarloCocozza** [Pandora-IsoMemo/resources#37]
[Cluster 1.zip](https://github.com/Pandora-IsoMemo/resources/files/8845744/Cluster.1.zip)
[Cluster 2.zip](https://github.com/Pandora-IsoMemo/resources/files/8845745/Cluster.2.zip)

For the attached models, "User estimates Calories", "User estimates Protein", "User estimates Carblipds", and "User estimates Macros", show unrealistic values. These also are not normalized. However, this does not happen for the "Source contribution" estimates, which looks consistent with previous models for the same data.

@arunge

**Comment by mgross** [comment]
Thanks for reporting, that was a edge case when you selected the first model type (info shared). Will be fixed in next version

**Comment by arunge** [comment]
The fixes are available on the beta branch: https://isomemoapp.com/app/resources-beta
@CarloCocozza Could you check if all is correct now?

**Comment by CarloCocozza** [comment]
@arunge This looks correct to me now. Thanks!
