### ISSUE TITLE
URGENT: interface links malfunction/saved files not working

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/resources#44]
@arunge I am having problems again with the automated updates in ReSources. As I requested previously please shut these down unless essential. 

From my understanding, automated data links are ONLY needed for:

Option to select Proxy under Sources under the tab "Data" 
Prior info names
User estimates names

Other than for these elements there should be no data links! 

- [ ] **Point 1**

If a user has already added a prior or an estimate and then changes the sources names, the names being listed as options in prior/estimates sections are updated but NOT any defined priors/estimates.  See figure below:

![image](https://user-images.githubusercontent.com/46485054/177950948-c279ca69-2b13-45dc-ab1e-cec0f6528eac.png)

Currently the names for the options are NOT being updated if source names are changed! This should be fixed! It does not have to be automated, you could also do this via a button and add a warning when pressed: "Notice that names in already priors will not be updated and these likely will have to be defined again!"

- [x] **Point 2**

As mentioned above there is a necessary data link for the option to select Proxy under Sources under the tab "Data". See figure below

![image](https://user-images.githubusercontent.com/46485054/177953062-c741c874-a30f-4430-9880-a93bf42edf44.png)

Although the proxy selection is automatically updated this should not be the case for the data tables themselves! See Point 3 below!

- [x] **Point 3**

I tried to prepare a rather long model yesterday, all seemed to be working well until I reached the stage of entering data for concentrations. Once I did this there was an automated update for the tables under Sources. These tables were assigned zero columns and my data was deleted. I tried today a different model and the same happened again. This time I made a recording so that you could reproduce all inputs. The issue is shown around minute 7:

https://www.youtube.com/watch?v=OQsnTgwAL74

**Point 4**

Beyond solving the issue described in Point 3 please have a look for any other automated links/updates that could cause problems!

- [x] **Point 5**

The problems in saving models persit although they are random. I could upload the model that I saved today but the model from my yesterday's test causes the app to crash:

[2022-07-07_20 42 22_fruitsModel.zip](https://github.com/Pandora-IsoMemo/resources/files/9070499/2022-07-07_20.42.22_fruitsModel.zip)

**Point 6**

The default names for some of the table headers may confuse the users. Please update these:

![image](https://user-images.githubusercontent.com/46485054/177956910-581c6df6-5faf-4a86-8bc1-bf7fc9af04b9.png)

**Comment by arunge** [comment]
@isomemo The name changes in point 6 would also affect other tables. Is this desired, (1), (2), (3)?

![image](https://user-images.githubusercontent.com/16759098/178254955-7fdb7a44-7771-448d-8d22-e24518b6212d.png)
![image](https://user-images.githubusercontent.com/16759098/178255154-7dfa754e-fd12-4c00-89e1-8bee4e9be2d1.png)

**Comment by ldv1452** [comment]
@arunge I do not want to cause additional link issues and if so we can drop name changes. However, are these names truly being linked? I had requested before that these links were turned off (as with tasks above)

**Comment by arunge** [comment]
### "Sources" tab
- `targetNames` are used as default column names:
https://github.com/Pandora-IsoMemo/resources/blob/4d77448eded3c4fe6ec0a507d4340b932a41aaaf/R/01-ui.R#L165-L169

### "Concentrations" tab
- the default column names are also the `targetNames`:
https://github.com/Pandora-IsoMemo/resources/blob/4d77448eded3c4fe6ec0a507d4340b932a41aaaf/R/01-ui.R#L210-L216

I changed the `targetNames` from "proxy_1" to "proxy_or_component_1" to achieve the name change:
https://github.com/Pandora-IsoMemo/resources/blob/5fedccf77765789639d8a711c376f65a77a691e3/R/03-defaults.R#L137
https://github.com/Pandora-IsoMemo/resources/blob/5fedccf77765789639d8a711c376f65a77a691e3/R/03-defaults.R#L156-L158

 This effected the other two tabs:

### "Target & target-to-source offsets" tab
- matrices also use `targetNames` as default column and row names, respectively. 
https://github.com/Pandora-IsoMemo/resources/blob/4d77448eded3c4fe6ec0a507d4340b932a41aaaf/R/01-ui.R#L76
https://github.com/Pandora-IsoMemo/resources/blob/4d77448eded3c4fe6ec0a507d4340b932a41aaaf/R/01-ui.R#L82-L87

### "Components" tab:

- default column names of the matrix are the `fractionNames`:
https://github.com/Pandora-IsoMemo/resources/blob/4d77448eded3c4fe6ec0a507d4340b932a41aaaf/R/01-ui.R#L142

- -> `fractionNames` depend on user input: 
  - when components are included 
![image](https://user-images.githubusercontent.com/16759098/178279035-6b8d690a-82ae-40dc-a441-f498b6ce1ffb.png)
and if concentrations are available, then the column names of the concentrations are used (line 192).
https://github.com/Pandora-IsoMemo/resources/blob/4d77448eded3c4fe6ec0a507d4340b932a41aaaf/R/01-server.R#L190-L200

So, we must decide which default values should be used for the last two tabs. @isomemo Should we discuss this the next time?

**Comment by isomemo** [comment]
Ok! But these are just default names, right? That is, they are just strings being displayed without having an impact in the structure of the tables and subsequent modelling?

Given the urgency of the project it is important to fix ReSources. I can use the model with the names as they are above, if necessary. But is the main issues (concerning the deletion of columns) fixed?

**Comment by arunge** [comment]
> But is the main issues (concerning the deletion of columns) fixed?

Unfortunatelly, I could not identify the source of the problem yet. But I am trying to find the part causing the error.

**Comment by arunge** [comment]
@isomemo With version [22.07.3](https://isomemoapp.com/app/resources-beta) I fixed a bug in the source tab that caused the app to crash when uploading data. The bug only occurd if weights == 0 existed. Maybe this could explain the "randomness"?
Could you test uploading the file under Point 5? It worked when I tested it. Could you check the tab "Sources" carefully after the upload, and see if all is shown what you would expect to see?

**Comment by isomemo** [comment]
@arunge I managed to load the file but I am not fully certain that the randomness is only related with weights==0. 

Interestingly I could load the model with all data inputs. This suggest that the error with the disappearing columns did not erase the data. However, since I have additional models fixing this remains a priority.

Furthermore, and unfortunately, I could not run the model. I got this error: "Could not create model object. Received the following error: Error in checkDataNameConsistency(data, modelOptions) : 
  Component names of component and source data do not match. Please check your data"

These are the names of the components under the tab Components:

![image](https://user-images.githubusercontent.com/46485054/178320437-a19ffe1b-54fd-437c-9852-7a410d3a8616.png)

These are the component names under the table Sources:

![image](https://user-images.githubusercontent.com/46485054/178320605-9929e6d9-594d-40a6-9a52-fe03890fd721.png)

![image](https://user-images.githubusercontent.com/46485054/178320665-2b235386-2e2b-4138-bb80-a11348f9b378.png)

![image](https://user-images.githubusercontent.com/46485054/178320757-41230768-2b9b-455b-93fe-18e256890ff2.png)

![image](https://user-images.githubusercontent.com/46485054/178320833-bbf6666b-2a99-469b-b649-53c34f655e1c.png)

![image](https://user-images.githubusercontent.com/46485054/178320908-0b5d443d-7ade-40b6-aeba-39eed0d63664.png)

I cannot see any differences in naming components in the tables Components and Sources!

Also, for greater clarity please change this message when loading a model: "Model object is empty, no model output available. Only data and model inputs will be uploaded. Upload completed."

to: "Model selection and data loaded! The file does not include saved results."

**Comment by isomemo** [comment]
@arunge thanks for the update! I would be happy to follow your suggestions and alternatives to what I have proposed. We can discuss these or please send me a description. I will include these in the new contract although in the meantime you can take time from previous contract. I have two many requests:

1) This is, I believe, the 5th time that I am going to invest to fix repeating major interface issues in ReSources. Please go as deep as you find it necessary but I would like this to be the last time we invest on this. I can understand that minor bugs will always appear but we should use this opportunity to have an interface that works  well in c. 95% of the cases. The tests we have made so far are only for the basic cases and I anticipate many more bugs.

2) Before doing any changes that may impact model definition please consult with Marcus just so that you are certain that model estimates will not be modified after the interface code is modified.

**Comment by arunge** [comment]
@isomemo Please note: https://github.com/Pandora-IsoMemo/resources/pull/51#issuecomment-1191198523

> I merged new tests from the main and beta branch into this feature branch. All tests are succeeding currently. 
>
> However, before merging here, I will add tests that will check if the modularising of the tabs `targetValues, components, sources, concentrations` broke something or if the result remains the same.
>
> Just to be sure that the app will still work as expected.

That is, I will only manage to merge the fix regarding Point 3 after my holidays, that is in around three weeks from today on.

**Comment by arunge** [comment]
I merged a new [version 22.08.2](https://github.com/Pandora-IsoMemo/resources/pull/51#issue-1308337172) into the [beta branch](https://isomemoapp.com/app/resources-beta) fixing point 3 from above.

**Comment by arunge** [comment]
The open points 1 and point 6 are discussed in a new issue: https://github.com/Pandora-IsoMemo/resources/issues/55. I close here.
