### ISSUE TITLE
MCMC model options bug

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/resources#48]
@mgross 

I ran this model without a problem using default MCMC options:
[2022-07-18_11 52 42_fruitsModel.zip](https://github.com/Pandora-IsoMemo/resources/files/9131123/2022-07-18_11.52.42_fruitsModel.zip)
 
I then changed the MCMC options (values in figure below) and got the following error:

![image](https://user-images.githubusercontent.com/46485054/179490905-96a2d9fa-ad22-4fb9-be11-8127fce01602.png)

**Comment by isomemo** [comment]
@mgross I narrowed down the issue. It seems to be related only with the number of chains

**Comment by mgross** [comment]
@isomemo fixed in beta 22.08.1.0 (was introduced with BIC-measure)

**Comment by isomemo** [comment]
Thanks!
