### ISSUE TITLE
Display bug

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/resources#49]
@arunge 

In the new ReSources interface the left panel is not fully visible and cannot be scrolled:

![image](https://user-images.githubusercontent.com/46485054/179491580-119e3577-d688-44e9-9b16-8c48f4cfceda.png)

Also please rename "Load model" to "Load local model" and move this option above "Select example model"

Finally, rename "Select example model" as "Load online model"

**Comment by arunge** [comment]
@isomemo With version 22.8.2 on the beta app I added scrolling to the left sidebar. However, this required to fix the hight of the sidebar which can lead to problems for smaller resolutions. Hopefully, the fix covers the most issues. If this is still an issue I must dive deeper into css code for shiny. The options given within shiny are limited.
