### ISSUE TITLE
[MPI_erweiterung_priority_055]: ReSource. Help button should point to online pdf file with a fixed filename and available in an online directory #390

### ISSUE THREAD

**Issue by jroachell15** [Pandora-IsoMemo/resources#5]
Original ticket: https://github.com/INWT/mpi-resources/issues/390

The current apps now have help buttons that once pressed show an outdated or no text. Instead, these should point to an online pdf file with a fixed filename and available in an online directory. Also to be implemented in new apps. This pdf file should also be accessible in the Desktop version, provided, of course, there is an internet connection.

# Please also do this for ALL apps:

- [ ] AssignR
- [ ] PlotR
- [ ] BPred
- [ ] OsteoBioR
- [ ] Pandora/Isomemo

Andreas update:  will need to ask Ricardo whether he has these PDFs have paths? We need to hard code the filenames in the app.

**Comment by arunge** [comment]
An updated version of this task will be part of the new tasks. New Buttons "About" and "Help" should point on pdf files that will be stored at github.

**Comment by arunge** [comment]
This task will be implemented within https://github.com/Pandora-IsoMemo/data-tools/issues/23.
