### ISSUE TITLE
IMPORTANT question on convergence chains

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/resources#50]
@mgross Please confirm that estimates are made for full MCMC options. I ask this since:

1) If I export convergence chains these contain 10,000 steps
2) The convergence graph shows 2,000 steps
3) Please also confirm, just to be 100% certain, that burn-in in steps are not included in graphs/exported chains

**Comment by mgross** [comment]
@isomemo:

1 + 2.: It can be confusing, but is logical. One Example:

Five Sources model 3 chains, 10.000 iterations and thinning of 10. For each parameter you have 3 * 10000/10 = 3000 iterations eventually. 
So in Model Diagnostics, if you choose e.g. 
Select group of estimates --> Source contributions
Display by -->Estimate
Select category ..>Target
Target-> Individual 1
Select estimates: Herbivores, Carnivores, Plants, Fish1 +2

Then you see 3000 iter (5 chains as 1 chain for each estimate) in the graph, but with export data you get 15000 rows as you have 5 estimates (Herbivores, Carnivores, Plants, Fish1 +2) selected.

3. no burn-in included 100% certain

-----------------------
These are individual chains plotted as one concatenated chain , not averaged! I am not sure if averaged chains make sense (but possible).

**Comment by isomemo** [comment]
All is clear now! In a new task the user will be able to select how many draws are to be shown.
