### ISSUE TITLE
Bug for Target & Source summary under Model characteristics

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/resources#52]
@mgross  See error below when trying the model "5 sources data":

![image](https://user-images.githubusercontent.com/46485054/182134754-82a6ed00-6580-48f4-8a5d-a9966f441d27.png)

**Comment by mgross** [comment]
@isomemo Fixed in beta 22.08.1.0

**Comment by isomemo** [comment]
Thanks!
