### ISSUE TITLE
Cannot run the example (or any other) model

### ISSUE THREAD

**Issue by mbrabec1** [Pandora-IsoMemo/resources#56]
I choose Five Sources Data and Load selected model, then I press the Run button
There I get an error message window saying:
Could not run model. Received the following error: Error : failed to create the shared library. Run ‘printErrors()’ to see the compilation errors.
Details are in the attached Word file.
Thanks for help!
 mbrabec1
[ReSources actions.docx](https://github.com/Pandora-IsoMemo/resources/files/9585625/ReSources.actions.docx)

**Comment by mbrabec1** [comment]
Dear Antonia,

here is the pdf of the document that was attached as a Word file.

All the Best

Marek

**Comment by arunge** [comment]
Dear @mbrabec1,
it looks like you replied directly via e-mail. Unfortunately, the pdf was not attached to the issue in github. Could you please upload the pdf or the content directly into this issue?

**Comment by mbrabec1** [comment]
Here is the pdf.
All the Best
 Marek
[ReSources actions.pdf](https://github.com/Pandora-IsoMemo/resources/files/9624765/ReSources.actions.pdf)

**Comment by arunge** [comment]
@mbrabec1 Sorry, for not replying for so long. Possibly you found a solution. We updated our instructions on how to install the apps on different systems:
- https://github.com/Pandora-IsoMemo/resources/wiki/Local-install-instructions

We recommend to use the [installation with docker](https://github.com/Pandora-IsoMemo/resources/wiki/Local-install-instructions#install-app-in-a-docker-container-preferred). This prevents issues that can occur when installing R-packages on different systems.

Please feel free to open a new issue in case of problems.

**Comment by mbrabec1** [comment]
Thanks.

Marek
