### ISSUE TITLE
[MPI_erweiterung_priority_048]: ReSource. Save and load files fully describing models plus a text describing model #389

### ISSUE THREAD

**Issue by jroachell15** [Pandora-IsoMemo/resources#6]
original ticket: https://github.com/INWT/mpi-resources/issues/389

User will be able to save and load files fully describing models plus a text describing the model (text entered by user before saving) for apps ReSources /OsteoBioR /Bpred/ IsoMemo models. 
- [x] The saved files should be loadable directly into R so that a user may execute the models within the R environment 
- [x] (this should include the description of the different functions accessible via help). 
- [x] The user will also be able to load files available from a directory online (for the Desktop version of the apps this will require an internet connection). The files for each app/model will be stored in a separate online directory. These individual directories will be contained within a single directory. In the app interface files stored in an online directory are displayed in a pending list showing their names (without extension). The user selects one of these and presses load to load it.

ReSources: almost all of the above already implemented 
- [x] although need to ensure that all model options are saved as expected (e.g. “include source specific offsets” or model selection not being saved). 
- [x] The example files are to be made available as described above. 
- [x] In addition, within ReSources we also have the display of “Data tables”. The current display of these as individual buttons should be replaced by a pending list that would show the names of Excel files (without extension) stored in a directory (different from that for the ReSources models). The data display of these data files within ReSources should be kept as is with all existing options. However, I point out that the name and number of columns within the data files may change during updates. These data files should also be available in the desktop version provided there is internet access.

---
- current online directory (inside this repository): https://github.com/Pandora-IsoMemo/resources/tree/feat/6_uploadPresaved/inst/app/predefinedModels

**Comment by jroachell15** [comment]
full update here: https://github.com/INWT/mpi-resources/issues/389

the latest update: 
Just talked with @aneudecker: the feature of down/uploading a model was implemented before the "hidden tabs" (1) were added by @mgross. Most likely it is a missing feature that all inputs of the "hidden tabs" (3) are updated after uploading a model object (2).

![image](https://user-images.githubusercontent.com/16759098/153209144-f3bde031-ace6-412c-aa11-7b4fcfa8877f.png)

Note: In order to update all missing inputs it requires to save the whole model object `model()` which is generated after pressing the "run" button. This is currently not saved.

**Comment by arunge** [comment]
The **UI** and the **logic** of the feature to upload/download models is also targeted in https://github.com/Pandora-IsoMemo/resources/issues/15#issuecomment-1096594801. It will be continued there in #15 

@isomemo I close this ticket here.
