### ISSUE TITLE
Resources: Deploy Changes from Beta into Main App

### ISSUE THREAD

**Issue by arunge** [Pandora-IsoMemo/resources#60]
The main was not updated for a while. In the meanwhile 
- several bugs where fixed on the beta (#33, #44, #12, #49, #53, #43),
- and some features were added (#42, #23)

However, [updates regarding oxcal](https://github.com/Pandora-IsoMemo/resources/issues/7#issuecomment-1160824874) were added but are not finished yet. On the other side, this is also not working as expected on the Main version.

@isomemo I would like to push all the bug fixes and features mentioned above to the Resources main app. Is that ok for you?

**Comment by isomemo** [comment]
@arunge you can push the changes! I am creating a document for Marcus to fix the bugs. This has priority and we fix the OxCal output later on.

**Comment by arunge** [comment]
[Updates](https://github.com/Pandora-IsoMemo/resources/pull/61) from beta are on main.
