### ISSUE TITLE
URGENT: bug entering values

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/resources#64]
@arunge 

See the video: https://youtu.be/nPWeLkAU4u0

**Comment by arunge** [comment]
@isomemo I prepared a fix for this issue, currently some automatic checks are running. I can merge after they passed.

**Comment by arunge** [comment]
@isomemo  The fix is online with version [22.11.3on beta](https://isomemoapp.com/app/resources-beta).
