### ISSUE TITLE
Bug with user estimates (and priors?)

### ISSUE THREAD

**Issue by CarloCocozza** [Pandora-IsoMemo/resources#75]
[2023-02-09_15_38_04_fruitsModel.zip](https://github.com/Pandora-IsoMemo/resources/files/10698745/2023-02-09_15_38_04_fruitsModel.zip)

For the attached model, when a user estimate is added, the following error message appears:
![BUg User estimates](https://user-images.githubusercontent.com/101706974/217862454-3f4732a6-7a78-44b2-988e-8d1da9a01b94.png)

The same message also appeared when I tried to use a prior. However, in a different attempt, this did not appear.

@arunge

**Comment by mgross** [comment]
Dear @CarloCocozza: this is probably some work, but can you try naming the individuals without "-" ? You could replace them by underscores. 

The main problem here is that parsing fails as we can't really distinguish between what is a name and what is a minus, especially as between two "-" there are numbers.

**Comment by arunge** [comment]
@CarloCocozza This issue was not touched for a while. Is the [above solution](https://github.com/Pandora-IsoMemo/resources/issues/75#issuecomment-1455897087) suggested by @mgross ok for you?

Can we close here?
