### ISSUE TITLE
No installation instructions

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/resources#78]
@arunge This repository does not contain installation instructions. I was under the impression that all repositories now have installation instructions?

**Comment by arunge** [comment]
The instructions can be found here: https://github.com/Pandora-IsoMemo/resources/wiki/Getting-started

Should we rename the respective page to e.g. "Installation instructions"?

**Comment by isomemo** [comment]
@arunge yes rename to "Local install instructions"

**Comment by arunge** [comment]
Will be completed within 
- https://github.com/Pandora-IsoMemo/drat/issues/23
