### ISSUE TITLE
Model not running with one proxy

### ISSUE THREAD

**Issue by CarloCocozza** [Pandora-IsoMemo/resources#83]
![Bug model only Nitrogen](https://user-images.githubusercontent.com/101706974/223997341-49f08bd4-a177-44d8-a009-e4e3aac7558d.png)
[2023-03-09_11_21_30_fruitsModel.zip](https://github.com/Pandora-IsoMemo/resources/files/10930421/2023-03-09_11_21_30_fruitsModel.zip)

For the attached model, I receive the attached error message. It seems that the model cannot run if there is only one proxy.

@arunge

**Comment by mgross** [comment]
@CarloCocozza Thanks for reporting this, I found the issue. @arunge I opened a pull request.

**Comment by arunge** [comment]
Is online with [version 23.03.4](https://github.com/Pandora-IsoMemo/resources/pull/90) on [resources beta](https://isomemoapp.com/app/resources-beta).
