### ISSUE TITLE
Issue with Copy-pasting in Target & target-to-source offsets table

### ISSUE THREAD

**Issue by CarloCocozza** [Pandora-IsoMemo/resources#99]
[Pergamon Roman.zip](https://github.com/Pandora-IsoMemo/resources/files/12455617/Pergamon.Roman.zip)

For the attached model, the software crashes when new data is copy-pasted in Target & target-to-source offsets table. This happens in all versions online and local.

@arunge

**Comment by arunge** [comment]
@CarloCocozza Could you provide more details on this? I did the following which was working without any issues:

1. Importing your data.
2. Copying a table (1) into a table calculation

| copy | paste |
|---|---|
|![image](https://github.com/Pandora-IsoMemo/resources/assets/16759098/4ccff473-a075-4132-8625-d970a03207d0)|![image](https://github.com/Pandora-IsoMemo/resources/assets/16759098/7fbd1974-14b3-4b1b-91a0-30886755382f)|

4. Changing some values, copying the table and pasting it into the app

| change & copy | paste back |
|---|---|
|![image](https://github.com/Pandora-IsoMemo/resources/assets/16759098/38f9233c-041a-4f6f-b7b4-9959c0519ac0)|![image](https://github.com/Pandora-IsoMemo/resources/assets/16759098/4059d859-f4c1-43f9-ac1b-085ada2b82ed)|

The app did not crash, I tested this on Resources main online.

Did you try something else that lead to the crash?

**Comment by CarloCocozza** [comment]
hi @arunge 

I sent this in a rush and I did not explained it properly. I meant when I copy-paste different data from an external file (in my case excel file), using ctrl-V.

**Comment by arunge** [comment]
Ok, now I could identify a problem that happens when the number of rows to be inserted is smaller than the number of rows that is already in the table. I am looking for a fix.

**Comment by arunge** [comment]
With [version 23.07.2](https://github.com/Pandora-IsoMemo/resources/pull/105) on [Resources beta](https://isomemoapp.com/app/resources-beta) I fixed the above bug that stopped the app working.

Now, one can paste a table into the target table, even if it contains targets that were not present in the table before. (I used your example data.)

![image](https://github.com/Pandora-IsoMemo/resources/assets/16759098/7a43edcb-3bb2-4afa-bac6-bf9c75d41428)

However, what should be the standard behavior for Sources and Concentration tables?
@isomemo @CarloCocozza  Should row and column names be kept after pasting a new target table? This is currently the case in version 23.07.2.

| Sources table | Concentrations table |
|---|---|
|![image](https://github.com/Pandora-IsoMemo/resources/assets/16759098/7f3921f1-ee2f-4040-9cef-701a4a5f75e2)|![image](https://github.com/Pandora-IsoMemo/resources/assets/16759098/97553a0a-82b3-4ed7-9cdd-d515f00ecff4)|

**Comment by arunge** [comment]
As just discussed, the current default behavior is fine and I am closing here.
